import Foundation

enum KeychainError: Error {
    case keyNotFound
}

enum KeychainManager {

    /// Returns the AES-256 key embedded at build time by the fl_env CLI.
    ///
    /// `FlEnvKey.swift` is generated by `fl_env build` and is intentionally
    /// gitignored. The project will not compile unless `fl_env build` has been
    /// run first.
    ///
    /// Phase 2 migration: replace with a Keychain `SecItemCopyMatching` call
    /// so the key is stored in the Secure Enclave rather than in the binary.
    static func getKey() throws -> [UInt8] {
        return FlEnvKey.bytes
    }
}
