package com.pixmerc.fl_env.keystore

import com.pixmerc.fl_env.generated.FlEnvKey

/**
 * Provides the AES-256 key that was embedded at build time by the fl_env CLI.
 *
 * [FlEnvKey] is generated by `fl_env build` and is intentionally gitignored.
 * The project will not compile unless `fl_env build` has been run first.
 */
internal object KeyManager {
    fun getKey(): ByteArray = FlEnvKey.bytes.clone()
}
